# Generated by Django 6.0.3 on 2026-04-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('ano', models.IntegerField()),
                ('situacao', models.CharField(choices=[('disponivel', 'Disponivel'), ('reservado', 'Reservado'), ('vendido', 'Vendido')], default='disponivel', max_length=20)),
            ],
        ),
    ]
